# Cloud Build for unified-domain-services
# Depends on: unified-cloud-services (from Artifact Registry)

steps:
  - name: 'python:3.13-slim'
    id: 'lint'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install uv
        pip install ruff==0.15.0
        ruff check .
        ruff format --check .

  - name: 'python:3.13-slim'
    id: 'build-wheel'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        pip install uv build keyring keyrings.google-artifactregistry-auth
        mkdir -p /root/.config/pip
        echo "[global]
        extra-index-url = https://asia-northeast1-python.pkg.dev/central-element-323112/unified-libraries/simple/" > /root/.config/pip/pip.conf
        uv pip install --system unified-cloud-services
        uv pip install --system -e ".[dev]"
        python -m build --wheel --outdir dist/
        ls -lh dist/
    waitFor: ['lint']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    id: 'store-metadata'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        apk add --no-cache python3
        WHEEL_FILE=$$(ls dist/*.whl)
        VERSION=$$(echo $$WHEEL_FILE | sed -n 's/.*-\([0-9.]*\)-.*/\1/p')
        echo "{\"version\":\"$$VERSION\",\"commit\":\"$COMMIT_SHA\"}" > /tmp/build-metadata.json
        gsutil cp /tmp/build-metadata.json gs://$PROJECT_ID-build-metadata/unified-domain-services/versions/$$VERSION.json || true
    waitFor: ['build-wheel']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    id: 'publish-python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        apk add --no-cache python3 py3-pip jq
        pip3 install --break-system-packages twine keyrings.google-artifactregistry-auth

        WHEEL_FILE=$$(ls dist/*.whl)
        VERSION=$$(echo $$WHEEL_FILE | sed -n 's/.*-\([0-9.]*\)-.*/\1/p')

        EXISTING_VERSIONS=$$(gcloud artifacts versions list \
          --package=unified-domain-services \
          --repository=unified-libraries \
          --location=asia-northeast1 \
          --format="value(VERSION)" 2>/dev/null || echo "")

        if echo "$$EXISTING_VERSIONS" | grep -qx "$$VERSION"; then
          if gsutil cp gs://$PROJECT_ID-build-metadata/unified-domain-services/versions/$$VERSION.json /tmp/existing-metadata.json 2>/dev/null; then
            EXISTING_COMMIT=$$(jq -r '.commit' /tmp/existing-metadata.json)
            if [ "$$EXISTING_COMMIT" = "$COMMIT_SHA" ]; then
              echo "✓ Version $$VERSION already published from commit $COMMIT_SHA (idempotent)"
              exit 0
            fi
          fi
          echo "❌ Version $$VERSION exists with different commit - bump version"
          exit 1
        fi

        python3 -m twine upload --repository-url https://asia-northeast1-python.pkg.dev/$PROJECT_ID/unified-libraries/ --non-interactive dist/*.whl
        echo "✓ Published unified-domain-services $$VERSION"
    waitFor: ['store-metadata']

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '600s'
